name: build-and-release-filters

on:
  push:
    paths:
      - "**/*.rs2f"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir output
          echo "Building filter"
          cat module_order.txt | while read line || [[ -n $line ]]; do
            echo "meta { name = \"Joe's filter\"; }" >> output/filter.rs2f
            cat modules/$line.rs2f >> output/filter.rs2f
          done
          echo "Building default filter"
          cat module_order.txt | while read line || [[ -n $line ]]; do
            echo "meta { name = \"[default: Joe's filter]\"; }" >> output/default-filter.rs2f
            cat modules/$line.rs2f >> output/default-filter.rs2f
          done

      - name: Print filter
        run: cat output/filter.rs2f

      - name: Print default filter
        run: cat output/default-filter.rs2f

      - name: Compute vars
        id: vars
        run: |
          echo "date=$(date +%Y%m%d.%H%M%S)" >> $GITHUB_OUTPUT
          echo "make_latest=false" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "make_latest=true" >> $GITHUB_OUTPUT
          fi

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ steps.vars.outputs.date }}
          make_latest: ${{ steps.vars.outputs.make_latest }}
          files: |
            output/filter.rs2f
            output/default-filter.rs2f
