name: build-and-commit-filters

on:
  push:
    paths:
      - "**/*.rs2f"
      - "module_order"
      - ".github/workflows/build-and-commit-filters.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Cleanup
        run: |
          echo "Cleaning up previously built filter files"
          rm -f filter.rs2f default-filter.rs2f

      - name: Compute vars
        id: vars
        run: |
          echo "short_commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "current_date_and_time=$(date)" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          echo "Building filter"
          header_module='/*@ define:module:header hidden: true name: header */'
          built_on_string="/* Built on: ${{ steps.vars.outputs.current_date_and_time }} */"
          commit_string="/* Commit: ${{ steps.vars.outputs.short_commit }} */"
          meta_string="meta {\n    name = \"Joe's filter\";\n    description = \"Offers an original color scheme with extensive support for category-based styling/filtering.\";\n}\n"
          echo -e "$header_module" >> filter.rs2f
          echo -e "$built_on_string" >> filter.rs2f
          echo -e "$commit_string" >> filter.rs2f
          echo -e "$meta_string" >> filter.rs2f
          cat module_order | while read line || [[ -n $line ]]; do
            cat modules/$line.rs2f >> filter.rs2f
          done

          echo "Building default filter"
          default_meta_string="meta {\n    name = \"[default: Joe's filter]\";\n    description = \"Offers an original color scheme with extensive support for category-based styling/filtering.\";\n}\n"
          echo -e "$header_module" >> default-filter.rs2f
          echo -e "$built_on_string" >> default-filter.rs2f
          echo -e "$commit_string" >> default-filter.rs2f
          echo -e "$default_meta_string" >> default-filter.rs2f
          cat module_order | while read line || [[ -n $line ]]; do
            cat modules/$line.rs2f >> default-filter.rs2f
          done

      - name: Print filter
        run: cat filter.rs2f

      - name: Print default filter
        run: cat default-filter.rs2f

      - name: Commit files
        run: |
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Build filters (sha: ${{ steps.vars.outputs.short_commit }})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref_name }}
