name: build-and-release-filters

on:
  push:
    paths:
      - "**/*.rs2f"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: just checking
        run: ls -alh
      - name: Build
        run: |
          mkdir output
          echo "Building filter"
          cat module_order.txt | while read line || [[ -n $line ]]; do
            echo "meta { name = \"Joe's filter\"; }" >> output/filter.rs2f
            cat modules/$line.rs2f >> output/filter.rs2f
          done
          echo "Building default filter"
          cat module_order.txt | while read line || [[ -n $line ]]; do
            echo "meta { name = \"[default: Joe's filter]\"; }" >> output/default-filter.rs2f
            cat modules/$line.rs2f >> output/default-filter.rs2f
          done
      - name: Print filter
        run: cat output/filter.rs2f
      - name: Print default filter
        run: cat output/default-filter.rs2f
      - name: Compute short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check short sha
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          make_latest: false
          files: |
            output/filter.rs2f
            output/default-filter.rs2f
