name: build-and-release-filters

on:
  push:
    paths:
      - "**/*.rs2f"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        run: |
          echo "Cleaning up previously built filter files"
          rm -rf output
          mkdir output

      - name: Build
        run: |
          echo "Building filter"
          cat module_order.txt | while read line || [[ -n $line ]]; do
            echo "meta { name = \"Joe's filter\"; }" >> output/filter.rs2f
            cat modules/$line.rs2f >> output/filter.rs2f
          done
          echo "Building default filter"
          cat module_order.txt | while read line || [[ -n $line ]]; do
            echo "meta { name = \"[default: Joe's filter]\"; }" >> output/default-filter.rs2f
            cat modules/$line.rs2f >> output/default-filter.rs2f
          done

      - name: Print filter
        run: cat output/filter.rs2f

      - name: Print default filter
        run: cat output/default-filter.rs2f

      - name: Compute vars
        id: vars
        run: |
          echo "date=$(date +%Y%m%d.%H%M%S)" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Build filters (sha: ${{ steps.vars.outputs.sha }})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
